### ISSUE TITLE
Reexport v0.2 compatibility requirement causing issues with other packages

### ISSUE THREAD

**Issue by ThatcherC** [JuliaNLSolvers/OptimBase.jl#16]
Hello! I recently tried to use the package `LsqFit` (which has `OptimBase` as a dependency) alongside the package [`SatelliteToolbox.jl`](https://github.com/JuliaSpace/SatelliteToolbox.jl) and encountered an unsatisfiable requirement error for the package `Reexport`. I posted a longer comment on an issue in `SatelliteToolbox` (https://github.com/JuliaSpace/SatelliteToolbox.jl/issues/51#issuecomment-842433280) but the issue is below:

```
(@v1.6) pkg> add SatelliteToolbox@v0.8.0
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Reexport [189a3867]:
 Reexport [189a3867] log:
 ├─possible versions are: 0.2.0-1.0.0 or uninstalled
 ├─restricted by compatibility requirements with SatelliteToolbox [6ac157d9] to versions: 1.0.0
 │ └─SatelliteToolbox [6ac157d9] log:
 │   ├─possible versions are: 0.3.0-0.8.0 or uninstalled
 │   └─restricted to versions 0.8.0 by an explicit requirement, leaving only versions 0.8.0
...
```

Both `OptimBase` and `SatelliteToolbox` have requirements for particular versions of `Reexport`, and `OptimBase`'s required version is older. Would the `OptimBase` team consider updating to the new (Jan 4, 2021), 1.0.0 stable release of `Reexport` over the current 0.2.0 (Aug 7, 2018) version? I imagine there are other packages that could encounter this same compatibility problem so I'm sure updating `Reexport` would solve the same problem for a lot of other users as well. The diff between the the 0.2.0 and 1.0.0 versions looks pretty small (see [here](https://github.com/simonster/Reexport.jl/compare/v0.2.0...1.0.0), so I would hope it's a relatively minor update to make the OptimBase. I actually see that @NicholasWMRitchie has a PR open for this already on https://github.com/JuliaNLSolvers/OptimBase.jl/pull/15, so merging that might do the trick.

Thanks for maintaining this great project!
-Thatcher

**Comment by pkofod** [comment]
Thanks for opening the issue and thanks @NicholasWMRitchie for making the PR.

**Comment by ThatcherC** [comment]
Awesome! I'm now able to use the latest versions of SatelliteToolbox and LsqFit together which is a huge help. Thanks everyone!

**Comment by pkofod** [comment]
> Awesome! I'm now able to use the latest versions of SatelliteToolbox and LsqFit together which is a huge help. Thanks everyone!

Sorry for the delay. Please do ping me on slack if any issues remain.
